# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/foyjog/Downloads/CLion-2021.2.3/clion-2021.2.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/foyjog/Downloads/CLion-2021.2.3/clion-2021.2.3/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/foyjog/Desktop/tmp/libbpf-bootstrap/examples/c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/foyjog/Desktop/tmp/libbpf-bootstrap/examples/c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/foyjog/Downloads/CLion-2021.2.3/clion-2021.2.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/foyjog/Downloads/CLion-2021.2.3/clion-2021.2.3/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/foyjog/Desktop/tmp/libbpf-bootstrap/examples/c/CMakeFiles /home/foyjog/Desktop/tmp/libbpf-bootstrap/examples/c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/foyjog/Desktop/tmp/libbpf-bootstrap/examples/c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minimal

# Build rule for target.
minimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minimal
.PHONY : minimal

# fast build rule for target.
minimal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal.dir/build.make CMakeFiles/minimal.dir/build
.PHONY : minimal/fast

#=============================================================================
# Target rules for targets named libbpf-build

# Build rule for target.
libbpf-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libbpf-build
.PHONY : libbpf-build

# fast build rule for target.
libbpf-build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbpf-build.dir/build.make CMakeFiles/libbpf-build.dir/build
.PHONY : libbpf-build/fast

#=============================================================================
# Target rules for targets named uprobe

# Build rule for target.
uprobe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uprobe
.PHONY : uprobe

# fast build rule for target.
uprobe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uprobe.dir/build.make CMakeFiles/uprobe.dir/build
.PHONY : uprobe/fast

#=============================================================================
# Target rules for targets named bootstrap

# Build rule for target.
bootstrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bootstrap
.PHONY : bootstrap

# fast build rule for target.
bootstrap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/build
.PHONY : bootstrap/fast

#=============================================================================
# Target rules for targets named libbpf

# Build rule for target.
libbpf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libbpf
.PHONY : libbpf

# fast build rule for target.
libbpf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbpf.dir/build.make CMakeFiles/libbpf.dir/build
.PHONY : libbpf/fast

#=============================================================================
# Target rules for targets named fentry

# Build rule for target.
fentry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fentry
.PHONY : fentry

# fast build rule for target.
fentry/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fentry.dir/build.make CMakeFiles/fentry.dir/build
.PHONY : fentry/fast

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named kprobe

# Build rule for target.
kprobe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kprobe
.PHONY : kprobe

# fast build rule for target.
kprobe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kprobe.dir/build.make CMakeFiles/kprobe.dir/build
.PHONY : kprobe/fast

bootstrap.o: bootstrap.c.o
.PHONY : bootstrap.o

# target to build an object file
bootstrap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/bootstrap.c.o
.PHONY : bootstrap.c.o

bootstrap.i: bootstrap.c.i
.PHONY : bootstrap.i

# target to preprocess a source file
bootstrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/bootstrap.c.i
.PHONY : bootstrap.c.i

bootstrap.s: bootstrap.c.s
.PHONY : bootstrap.s

# target to generate assembly for a file
bootstrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bootstrap.dir/build.make CMakeFiles/bootstrap.dir/bootstrap.c.s
.PHONY : bootstrap.c.s

fentry.o: fentry.c.o
.PHONY : fentry.o

# target to build an object file
fentry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fentry.dir/build.make CMakeFiles/fentry.dir/fentry.c.o
.PHONY : fentry.c.o

fentry.i: fentry.c.i
.PHONY : fentry.i

# target to preprocess a source file
fentry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fentry.dir/build.make CMakeFiles/fentry.dir/fentry.c.i
.PHONY : fentry.c.i

fentry.s: fentry.c.s
.PHONY : fentry.s

# target to generate assembly for a file
fentry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fentry.dir/build.make CMakeFiles/fentry.dir/fentry.c.s
.PHONY : fentry.c.s

hello.o: hello.c.o
.PHONY : hello.o

# target to build an object file
hello.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.c.o
.PHONY : hello.c.o

hello.i: hello.c.i
.PHONY : hello.i

# target to preprocess a source file
hello.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.c.i
.PHONY : hello.c.i

hello.s: hello.c.s
.PHONY : hello.s

# target to generate assembly for a file
hello.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.c.s
.PHONY : hello.c.s

kprobe.o: kprobe.c.o
.PHONY : kprobe.o

# target to build an object file
kprobe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kprobe.dir/build.make CMakeFiles/kprobe.dir/kprobe.c.o
.PHONY : kprobe.c.o

kprobe.i: kprobe.c.i
.PHONY : kprobe.i

# target to preprocess a source file
kprobe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kprobe.dir/build.make CMakeFiles/kprobe.dir/kprobe.c.i
.PHONY : kprobe.c.i

kprobe.s: kprobe.c.s
.PHONY : kprobe.s

# target to generate assembly for a file
kprobe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kprobe.dir/build.make CMakeFiles/kprobe.dir/kprobe.c.s
.PHONY : kprobe.c.s

minimal.o: minimal.c.o
.PHONY : minimal.o

# target to build an object file
minimal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal.dir/build.make CMakeFiles/minimal.dir/minimal.c.o
.PHONY : minimal.c.o

minimal.i: minimal.c.i
.PHONY : minimal.i

# target to preprocess a source file
minimal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal.dir/build.make CMakeFiles/minimal.dir/minimal.c.i
.PHONY : minimal.c.i

minimal.s: minimal.c.s
.PHONY : minimal.s

# target to generate assembly for a file
minimal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/minimal.dir/build.make CMakeFiles/minimal.dir/minimal.c.s
.PHONY : minimal.c.s

uprobe.o: uprobe.c.o
.PHONY : uprobe.o

# target to build an object file
uprobe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uprobe.dir/build.make CMakeFiles/uprobe.dir/uprobe.c.o
.PHONY : uprobe.c.o

uprobe.i: uprobe.c.i
.PHONY : uprobe.i

# target to preprocess a source file
uprobe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uprobe.dir/build.make CMakeFiles/uprobe.dir/uprobe.c.i
.PHONY : uprobe.c.i

uprobe.s: uprobe.c.s
.PHONY : uprobe.s

# target to generate assembly for a file
uprobe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uprobe.dir/build.make CMakeFiles/uprobe.dir/uprobe.c.s
.PHONY : uprobe.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libbpf"
	@echo "... libbpf-build"
	@echo "... bootstrap"
	@echo "... fentry"
	@echo "... hello"
	@echo "... kprobe"
	@echo "... minimal"
	@echo "... uprobe"
	@echo "... bootstrap.o"
	@echo "... bootstrap.i"
	@echo "... bootstrap.s"
	@echo "... fentry.o"
	@echo "... fentry.i"
	@echo "... fentry.s"
	@echo "... hello.o"
	@echo "... hello.i"
	@echo "... hello.s"
	@echo "... kprobe.o"
	@echo "... kprobe.i"
	@echo "... kprobe.s"
	@echo "... minimal.o"
	@echo "... minimal.i"
	@echo "... minimal.s"
	@echo "... uprobe.o"
	@echo "... uprobe.i"
	@echo "... uprobe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

